language: node_js


node_js:
- "11"

services:
- docker

# before_install:
# -

script:
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
- mkdir tmp
- >
  pushd tmp &&
  curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v2.6.0/qemu-arm-static.tar.gz &&
  tar xzf qemu-arm-static.tar.gz &&
  popd
# build image
- docker build -t amanohikaru/build-arm-test:ci .
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker push amanohikaru/build-arm-test:ci
# - curl -X POST http://util.online:9000/api/webhooks/0f1c7be8-5763-4b8d-8cc1-e23b3fd1befb

